version: '3.1'

services:
  flask_app:
    build:
      context: ./vms
      dockerfile: Dockerfile
    container_name: VMS
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    networks:
      - vms_network

  mongodb:
    image: mongo
    container_name: VMS_MongoDB
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      - vms_network

networks:
  vms_network:
    driver: bridge
